apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: httpbin-test
spec:
  type: NodePort
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000